In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("finer_ord_train.csv")

In [21]:
lista = data[data["gold_label"]==1]["gold_token"].unique()
data[data["gold_label"]==1]

       gold_label  gold_token  doc_idx  sent_idx
5               1       Obama        0         0
17              1       Obama        0         0
50              1     Neville        0         1
143             1       Obama        0         3
215             1     Phyllis        0         4
...           ...         ...      ...       ...
80303           1  Varoufakis      158        20
80313           1     Giorgos      158        21
80360           1  Varoufakis      158        23
80421           1       Yanis      158        25
80475           1  Varoufakis      158        27

[821 rows x 4 columns]

In [22]:
lista = data[data["gold_label"]==2]["gold_token"].unique()
data[data["gold_label"]==2]

       gold_label  gold_token  doc_idx  sent_idx
51              2       Otuki        0         1
216             2     Wakiaga        0         4
254             2       Obama        0         5
300             2       Olaka        0         7
500             2    Kenyatta        0        14
...           ...         ...      ...       ...
79758           2  Varoufakis      158         1
79860           2     Tsipras      158         3
79997           2   Schaeuble      158         8
80182           2      Willis      158        13
80314           2  Varoufakis      158        21

[553 rows x 4 columns]

In [23]:
lista = data[data["gold_label"]==3]["gold_token"].unique()
data[data["gold_label"]==3]

       gold_label gold_token  doc_idx  sent_idx
28              3     Africa        0         0
52              3      Kenya        0         1
81              3    Nairobi        0         1
119             3       East        0         2
127             3      Kenya        0         3
...           ...        ...      ...       ...
80471           3  Cambridge      158        26
80478           3  Australia      158        27
80495           3     Greece      158        28
80519           3     Austin      158        28
80521           3     Greece      158        28

[966 rows x 4 columns]

In [24]:
lista = data[data["gold_label"]==4]["gold_token"].unique()
data[data["gold_label"]==4]

       gold_label gold_token  doc_idx  sent_idx
120             4     Africa        0         2
130             4       Road        0         3
133             4    Highway        0         3
136             4        Way        0         3
137             4      Among        0         3
...           ...        ...      ...       ...
76507           4          .      149        36
76599           4     Africa      150         3
76607           4     Africa      150         4
76617           4     Africa      150         5
80469           4     Anglia      158        26

[289 rows x 4 columns]

In [25]:
lista = data[data["gold_label"]==5]["gold_token"].unique()
data[data["gold_label"]==5]

       gold_label    gold_token  doc_idx  sent_idx
207             5         Kenya        0         4
212             5           KAM        0         4
294             5         Kenya        0         7
398             5          KPMG        0        10
401             5          East        0        10
...           ...           ...      ...       ...
80326           5  Halyvourgiki      158        21
80332           5      Moraitis      158        22
80452           5        Ethnos      158        25
80502           5    University      158        28
80515           5    University      158        28

[2026 rows x 4 columns]

In [26]:
lista = data[data["gold_label"]==6]["gold_token"].unique()
data[data["gold_label"]==6]

       gold_label     gold_token  doc_idx  sent_idx
208             6    Association        0         4
209             6             of        0         4
210             6  Manufacturers        0         4
295             6        Bankers        0         7
296             6    Association        0         7
...           ...            ...      ...       ...
80333           6         School      158        22
80503           6             of      158        28
80504           6         Athens      158        28
80516           6             of      158        28
80517           6          Texas      158        28

[1414 rows x 4 columns]